# Generated by Django 5.1.7 on 2025-03-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0014_remove_teammember_bio'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.service')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_services', to='about.teammember')),
            ],
            bases=('home.service',),
        ),
    ]
