# Generated by Django 5.1.7 on 2025-04-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
