# Generated by Django 5.1.7 on 2025-04-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
