# Generated by Django 5.1.7 on 2025-04-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disability_type',
        ),
    ]
