# Generated by Django 5.1.7 on 2025-03-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='نسبة الخصم (%)')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='discount_offers/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'عرض خصم',
                'verbose_name_plural': 'عروض الخصم',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.ImageField(upload_to='service_icons/', verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'شريحة',
                'verbose_name_plural': 'شرائح العرض',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='why_choose_us/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'لماذا تختارنا',
                'verbose_name_plural': 'لماذا تختارنا',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطبيب')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='home.specialty', verbose_name='التخصص')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع؟')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor', verbose_name='الطبيب')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.specialty', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'حجز موعد',
                'verbose_name_plural': 'حجوزات المواعيد',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='الأيقونة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('why_choose_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.whychooseus', verbose_name='لماذا تختارنا')),
            ],
            options={
                'verbose_name': 'عنصر لماذا تختارنا',
                'verbose_name_plural': 'عناصر لماذا تختارنا',
            },
        ),
    ]
