# Generated by Django 5.1.7 on 2025-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='special_offer_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية العرض الخاص'),
        ),
    ]
