# Generated by Django 5.1.7 on 2025-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_special_offer_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='special_offer_end',
        ),
    ]
