# Generated by Django 5.1.7 on 2025-04-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_service_special_offer_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
