# Generated by Django 5.1.7 on 2025-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_slide_options_alter_slide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_he',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
