# Generated by Django 5.1.7 on 2025-04-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slide_description_ar_slide_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description_he',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='subtitle_he',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_he',
        ),
    ]
