# Generated by Django 5.1.7 on 2025-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_slide_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'شريحة', 'verbose_name_plural': 'شرائح العرض'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
