# Generated by Django 5.1.7 on 2025-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_slide_options_alter_slide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='description_he',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_he',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='description_he',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
    ]
