# Generated by Django 5.1.7 on 2025-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_whychooseus_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='description_he',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='subtitle_he',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='title_he',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='description_he',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='title_he',
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_he',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
    ]
