# Generated by Django 5.1.7 on 2025-04-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_whychooseus_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_he',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_he',
        ),
    ]
