# Generated by Django 5.1.7 on 2025-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_service_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_he',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الخدمة'),
        ),
    ]
