# Generated by Django 5.1.7 on 2025-04-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_service_description_ar_service_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_he',
        ),
    ]
