# Generated by Django 5.1.7 on 2025-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(default='', null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_he',
            field=models.TextField(default='', null=True, verbose_name='الوصف'),
        ),
    ]
