# Generated by Django 5.1.7 on 2025-04-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
