# Generated by Django 5.1.7 on 2025-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About us', max_length=255)),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
