# Generated by Django 5.1.7 on 2025-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug for URLs', unique=True),
        ),
    ]
