# Generated by Django 5.1.7 on 2025-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
