# Generated by Django 5.1.7 on 2025-03-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_teammember_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
