# Generated by Django 5.1.7 on 2025-03-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
