# Generated by Django 5.1.7 on 2025-03-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
