# Generated by Django 5.1.7 on 2025-03-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_remove_teammember_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
