# Generated by Django 5.1.7 on 2025-03-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_teammember_bio_teammember_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
    ]
