# Generated by Django 5.1.7 on 2025-04-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_remove_teammember_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='working_hours',
        ),
    ]
